import BlogCard from "@/components/BlogCard";
import { getEntries } from "@/libs/contentful";
import {
  Button,
  Container,
  Grid,
  GridItem,
  HStack,
  Stack,
  Text,
} from "@chakra-ui/react";
import { Metadata } from "next";

// Definisikan tipe data untuk blog
interface Blog {
  title: string;
  slug: string;
  description: string;
  thumbnail?: string;
  author: string;
  category: string;
  content: string;
  createdAt: string;
}

// Definisikan tipe data untuk respons API
interface BlogResponse {
  data: Blog[];
  meta: { total: number; limit: number };
}

// Props untuk komponen Home
interface HomeProps {
  searchParams: { [key: string]: string | string[] | undefined };
}

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function Home({ searchParams }: HomeProps) {
  let blogs: BlogResponse = { data: [], meta: { total: 0, limit: 0 } };

  try {
    blogs = await getEntries(Number(searchParams.page) || 1);
  } catch (error) {}

  return (
    <main>\
      
      {/* METADATA */}
      <Container maxW="5xl">
        {/* JUMBOTRON */}
        <Stack alignItems="center" mt="10" textAlign="center">
          <Text fontSize={{ base: "2xl", md: "5xl" }} fontWeight="semibold">
            Education and Sports Blog
          </Text>
          <Text fontSize="lg" color="gray.600">
            A blog about education, sports, and knowledge-sharing.
          </Text>
        </Stack>

        {/* BLOG LIST */}
        <Grid
          templateColumns={{
            base: "repeat(1, 1fr)",
            md: "repeat(3, 1fr)",
          }}
          gap={6}
          mt="16"
          mb="10"
        >
          {blogs.data.length > 0 ? (
            blogs.data.map((blog: Blog, index: number) => {
              return (
                <GridItem key={index}>
                  <BlogCard
                    title={blog.title}
                    slug={blog.slug}
                    description={blog.description}
                    thumbnail={blog.thumbnail || "/default-thumbnail.jpg"} // Mengatasi error
                  />
                </GridItem>
              );
            })
          ) : (
            <Text textAlign="center" gridColumn="1 / -1">
              No blogs found.
            </Text>
          )}
        </Grid>

        {/* CTA BUTTONS */}
        <HStack spacing={4} my={7} justifyContent="center">
          <Button
            as="a"
            href="https://www.instagram.com/purwadhikaschool?igsh=NHUzcXE3dnl3Ymdu"
            target="_blank"
            rel="noopener noreferrer"
            colorScheme="pink"
            size="lg"
          >
            Follow Us
          </Button>
        </HStack>
      </Container>
    </main>
  );
}
